### PR TITLE
Change bot name & avatar

### PR DESCRIPTION
**Pull request by erich0123**
I added bot commands and api endpoint to change the bot's nickname per guild. It's not possible to change the bot's avatar per guild, however. For that I've added a global command and api endpoint that only the owner of the bot can execute.

I've added the bot owner check to the `change_bot_avatar` command but for the api endpoint `/mappings/bot_globals`, I've added a dependency called `bot_owner` with a `TODO` comment, which always denies access for now.

I've also added the Rally logo as a default avatar.

Issue #16

### CODE REVIEW

**Comment by RallyCreatorCoins** [comment]
@erich0123 It should be possible to change the bot's avatar - I've seen other bots allow it. 

Here's an example: 
image

If you're able to come up with a solution that requires extra time/resources we can compensate you fairly for that. It's important that the user has the ability to change the avatar though. 

Please let me know your thoughts.

- PhelpsGG

**Comment by erich0123** [comment]
Maybe these bots are self hosted? Afaik, it's not possible to change the bot's avatar per guild as it is treated as a regular user account, you can only change the nickname. I've gone through the API and couldn't find anything by googling either. I've asked in several Discord groups and forums as well, noone has an answer.

I could try to email Discord and ask them directly if they could add a feature like that.

**Comment by erich0123** [comment]
I've checked how mee6 does it and they just have their user's create their own but token, with allows them to change the avatar.

This should already be possible with the PR I've made.

**Comment by Ju99ernaut** [comment]
I believe mee6 achieves this by proxying the custom bot user that you create, so it's not exactly self-hosting, probably they use the bot token as authentication when they modify the bot's name, avatar and activity through the discord API.

**Comment by erich0123** [comment]
You're right, they start a new instance of the bot for each custom bot. I think this might be out of scope for this PR.

**Comment by Ju99ernaut** [comment]
Looks like I'll have to close this PR as this bounty has already been completed fully in #26 and CreatorCoinTools/rally-discordbot-dashboard#5.

**Pull request closed without merging**
